### ISSUE TITLE
Build on GHC 9.2

### ISSUE THREAD

**Issue by tdammers** [input-output-hk/kes-agent#13]
Build currently fails on GHC 9.2 due to a compilation error in typed-protocols.
